config/routes.rb
Rails.application.routes.draw do

  resources :places

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all.order(:name)
	end

	def show
		@place = Place.find params[:id]
		# id = params[:id]
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LekkerClass</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<h1>Hello! Welcome to Cape Town!</h1>
	
<% @places.each do |place| %>
	
	<div>
		<!-- <strong><%= place.name %></strong> -->
		<strong><%= link_to place.name, place_path(place) %></strong>
		<p> <%= place.description %></p>
	</div>

	
	<% end %>

app/views/places/show.html.erb
<strong><h><%= @place.name %></h></strong>
<p><%= @place.description %></p>
<p>Located at:<%= @place.address %></p>

<p><%= link_to 'All Places', places_path %></p>   <!-- #it doesn't take params -->  